name: "Build multiarch docker image"

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'

env:
  DUMMY: "3"

jobs:
  tag:
    name: Extract tag name
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ fromJSON(steps.tag.outputs.result) }}
    steps:
      - name: Extract the tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref === "refs/heads/master"
              ? 'latest'
              : context.payload.ref.replace(/^refs\/(tags|heads)\//, '');

  build:
    needs:
      - tag
    name: Build
    uses: pldin601/build-multiarch-on-aws-spots/.github/workflows/test.yml@a674d24b358b83f212ef7db4abd455b5929ec574
    with:
      DOCKER_IMAGE_TAG: ${{ needs.tag.outputs.TAG }}
      WORKFLOW_CHECKOUT: a674d24b358b83f212ef7db4abd455b5929ec574
      AWS_REGION: eu-west-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
