name: Build multi-arch image

on:
  push:
    tags:
      - *

jobs:
  tag:
    runs-on: ubuntu-18.04
    steps:
      - name: Extract the tag
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
  build:
    needs:
      - tag
    name: Build
    uses: pldin601/common-workflows/.github/workflows/build-multiarch-on-aws-spots.yml@v1.0.0
    with:
      DOCKER_IMAGE_TAG: ${{ needs.tag.outputs.TAG }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
